/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatChatIdRouteImport } from './routes/chat.$chatId'
import { Route as PrivateChatConversationIdRouteImport } from './routes/private-chat.$conversationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateChatConversationIdRoute =
  PrivateChatConversationIdRouteImport.update({
    id: '/private-chat/$conversationId',
    path: '/private-chat/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chats': typeof ChatsRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/private-chat/$conversationId': typeof PrivateChatConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chats': typeof ChatsRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/private-chat/$conversationId': typeof PrivateChatConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chats': typeof ChatsRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/private-chat/$conversationId': typeof PrivateChatConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/chats'
    | '/friends'
    | '/login'
    | '/requests'
    | '/settings'
    | '/chat/$chatId'
    | '/private-chat/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/chats'
    | '/friends'
    | '/login'
    | '/requests'
    | '/settings'
    | '/chat/$chatId'
    | '/private-chat/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/chats'
    | '/friends'
    | '/login'
    | '/requests'
    | '/settings'
    | '/chat/$chatId'
    | '/private-chat/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ChatsRoute: typeof ChatsRoute
  FriendsRoute: typeof FriendsRoute
  LoginRoute: typeof LoginRoute
  RequestsRoute: typeof RequestsRoute
  SettingsRoute: typeof SettingsRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
  PrivateChatConversationIdRoute: typeof PrivateChatConversationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-chat/$conversationId': {
      id: '/private-chat/$conversationId'
      path: '/private-chat/$conversationId'
      fullPath: '/private-chat/$conversationId'
      preLoaderRoute: typeof PrivateChatConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ChatsRoute: ChatsRoute,
  FriendsRoute: FriendsRoute,
  LoginRoute: LoginRoute,
  RequestsRoute: RequestsRoute,
  SettingsRoute: SettingsRoute,
  ChatChatIdRoute: ChatChatIdRoute,
  PrivateChatConversationIdRoute: PrivateChatConversationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
